### ISSUE TITLE
Missing information about moving swagger-ui to public

### ISSUE THREAD

**Issue by lordt** [Happycar/zf2-swagger-ui#1]
I assumed you based on https://packagist.org/packages/kbrabrand/zf2-swagger-ui 
In mentioned repo is information about creating symbolic link, in this there is not.

**Comment by MaiKaY** [comment]
Hi @lordt,
what do you mean exactly?
Is there something missing in our repository?

cheers
Maik

**Comment by lordt** [comment]
Hi @MaiKaY 

Installation description in README is incomplete. After finishing installation steps there are some files (`/vendor/happycar/zf2-swagger-ui/view/swagger-ui/*`) that should be placed in `public/` to display page at `/api` properly. 

In repo I mentioned earlier there is a tip to create symbolic link for files in `vendor/`, however that also isn't done correctly (link is created in root directory, not in `public/`).  This solution is good, but hard to do on Windows. In project where I used _Happycar/zf2-swagger-ui_ I've add one extra script in _post-update-cmd_ to copy files from `vendor/.../swagger-ui` to `public/`. I've also add those directory to `.gitignore`.

Regards
Paweł

**Comment by MaiKaY** [comment]
Hi @lordt,
the informations are not missing they are just _hidden_ - we need to improve that :-)
We mentioned a `suggest` in our `composer.json` for `rwoverdijk/assetmanager` as soon as you set the library to your own `composer.json` and add the `AssetManager` module to your application it should work. We already configured the module [here](https://github.com/Happycar/zf2-swagger-ui/blob/master/config/module.config.php#L48-L54)

Please let me know if everything works or either not.

best regards
Maik

**Comment by lordt** [comment]
@MaiKaY I've used Happycar/zf2-swagger-ui in project at work and think I wouldn't do any changes in future. I belive that `assetmanager`, which I've omited, is working:)
